### ISSUE TITLE
KeyError: 'defaultdisk' on OS X Yosemite / 10.10.2

### ISSUE THREAD

**Issue by lenix** [ployground/ploy_virtualbox#5]
I went down the "homebrew -> py-virtualenv -> git clone -> make -> pip install ploy_virtualbox -> quickstart" path, and that's what i ended up with:

```sh
(bsdploy)McLenix:ploy-quickstart lenix$ ploy start ploy-demo
INFO: Creating instance 'ploy-demo'
INFO: Adding default 'sata' controller.
Traceback (most recent call last):
  File "/Users/lenix/Projects/private/unixuni/bsdploy/bin/ploy", line 9, in <module>
    load_entry_point('ploy==1.0.3', 'console_scripts', 'ploy')()
  File "/Users/lenix/Projects/private/unixuni/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 540, in ploy
    return ctrl(argv)
  File "/Users/lenix/Projects/private/unixuni/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 532, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/Users/lenix/Projects/private/unixuni/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 284, in cmd_start
    result = instance.start(overrides)
  File "/Users/lenix/Projects/private/unixuni/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 327, in start
    medium = self.master.disks[medium[8:]].filename(self)
  File "/Users/lenix/Projects/private/unixuni/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 540, in __getitem__
    self._cache[key] = self.klass(key, self.config[key])
KeyError: 'defaultdisk'
(bsdploy)McLenix:ploy-quickstart lenix$ which python
/Users/lenix/Projects/private/unixuni/bsdploy/bin/python
(bsdploy)McLenix:ploy-quickstart lenix$ python --version
Python 2.7.6
(bsdploy)McLenix:ploy-quickstart lenix$ which pip
/Users/lenix/Projects/private/unixuni/bsdploy/bin/pip
(bsdploy)McLenix:ploy-quickstart lenix$ which ploy
/Users/lenix/Projects/private/unixuni/bsdploy/bin/ploy
(bsdploy)McLenix:ploy-quickstart lenix$ pip list
ansible (1.8.3)
ecdsa (0.13)
Jinja2 (2.7.3)
lazy (1.2)
MarkupSafe (0.23)
paramiko (1.15.2)
pip (1.5.6)
ploy (1.0.3)
ploy-virtualbox (1.1.0)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (12.2)
virtualenv (12.0.7)
wsgiref (0.1.2)
zc.buildout (2.3.1)
(bsdploy)McLenix:ploy-quickstart lenix$ uname -a
Darwin McLenix.private 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
(bsdploy)McLenix:ploy-quickstart lenix$ cat etc/ploy.conf 
[vb-instance:ploy-demo]
vm-nic2 = nat
vm-natpf2 = ssh,tcp,,44003,,22
storage =
    --medium vb-disk:defaultdisk
    --type dvddrive --medium http://mfsbsd.vx.sk/files/iso/10/amd64/mfsbsd-se-10.1-RELEASE-amd64.iso --medium_sha1 03af247c1058a78a251c46ad5a13dc7b84a7ee7d
(bsdploy)McLenix:ploy-quickstart lenix$ 
```

any hints?

**Comment by tomster** [comment]
which version of bsdploy are you using? in fact, bsdploy does not show up in your output above (except as the name of your virtualenv).

the ``defaultdisk`` behaviour is a bsdploy feature, it's neither part of ploy_virtualbox nor ploy itself.

hth

**Comment by tomster** [comment]
@lenix is this still an issue for you?

**Comment by Infiniverse** [comment]
Hi there, it is for me. I'm using the latest bsdploy from git, and also have this problem on Yosemite:

(bsdploy)unnamed-72:ploy-quickstart joe$ ploy start ploy-demo
INFO: Creating instance 'ploy-demo'
INFO: Adding default 'sata' controller.
Traceback (most recent call last):
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/bin/ploy", line 9, in <module>
    load_entry_point('ploy==1.2.0', 'console_scripts', 'ploy')()
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 557, in ploy
    return ctrl(argv)
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 549, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 284, in cmd_start
    result = instance.start(overrides)
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 327, in start
    medium = self.master.disks[medium[8:]].filename(self)
  File "/Users/joe/Documents/TrueSpeed/Ploy/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 540, in __getitem__
    self._cache[key] = self.klass(key, self.config[key])
KeyError: 'defaultdisk'

**Comment by Infiniverse** [comment]
I've got it working now. I think that the problem was environmental. I removed all references to virtualenv from my .profile, and rebuilt ploy, and now it works fine. Not sure which of those two things made the difference.

**Comment by tomster** [comment]
@Infiniverse yes, looks like there might have been an older version of ploy_virtualbox or bsdploy interfering.

at any rate i'm glad it's working for you and will close this issue since it's either working for @lenix , too or we've lost him along the way :)
